- name: Install Wallpaper
  hosts: target
  vars:
    src_wallpaper: "files/test.txt"
    dest_wallpaper: "/usr/share/wallpapers/"

    file_mode: '0644'
    backup_files: no

  tasks:
    - name: Copy Wallpaper
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: "{{ file_mode }}"
        backup: "{{ backup_files }}"
      loop:
        - { src: "{{ src_wallpaper }}", dest: "{{ dest_wallpaper }}" }
